-- Station spec fields: kw, connector, stalls, tariff
ALTER TABLE "stations" ADD COLUMN IF NOT EXISTS "kw" DOUBLE PRECISION NOT NULL DEFAULT 50;
ALTER TABLE "stations" ADD COLUMN IF NOT EXISTS "connector" TEXT NOT NULL DEFAULT 'CCS';
ALTER TABLE "stations" ADD COLUMN IF NOT EXISTS "stalls" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "stations" ADD COLUMN IF NOT EXISTS "tariff" DOUBLE PRECISION NOT NULL DEFAULT 20;
